embeddings_model:
  # Name of the sentence-transformer model to use for generating embeddings
  model_name: "all-MiniLM-L6-v2"
  # Whether to show a progress bar during embedding generation
  show_progress: True

embed_documents:
  # Directory where the computed document embeddings will be stored
  embeddings_path: "./data/embeddings/"
  # Name of the FAISS index file to store the vector database
  index_name: "faiss_index_got"
