embeddings_model:
  model_name: "all-MiniLM-L6-v2" # Name of the sentence-transformer model to use for generating embeddings
  show_progress: True # Whether to show a progress bar during embedding generation

embed_documents:
  embeddings_path: "./data/embeddings/" # Directory where the computed document embeddings will be stored
  index_name: "faiss_index_got" # Name of the FAISS index file to store the vector database
