defaults:
  # Indicates that this config file includes its own contents first
  - _self_

  # Includes default preprocessing configuration (from preprocessing/default.yaml)
  - preprocessing: default

  # Includes default embeddings configuration (from embeddings/default.yaml)
  - embeddings: default

  # Specifies the text splitting strategy to use (e.g., SemanticChunker)
  - text_splitter: semanticchunker
