path: "./data/datasets/books/" # Path to the directory containing the EPUB files
file_extension: ".epub" # File extension to filter files to process

whitespace: r"\s+" # Regex pattern to match one or more whitespace characters (tabs, newlines, etc.)
whitespace_replacement: " " # Replacement string for whitespace normalization (e.g., collapse multiple spaces to a single space)

url: r"http\S+|www\S+" # Regex pattern to detect URLs starting with http or www
url_replacement: "" # Replacement string for URLs (empty string means URLs will be removed)

non_alphanumeric: r"[^A-Za-z0-9\s\.,;:\'\"\?\!\-]" # Regex pattern to remove all non-alphanumeric characters except basic punctuation
non_alphanumeric_replacement: "" # Replacement string for non-alphanumeric characters (empty string means they will be removed)

consecutive_non_alphanumeric: r"([^A-Za-z0-9\s])\1+" # Regex pattern to collapse repeated non-alphanumeric characters (e.g., "!!!" → "!")
consecutive_non_alphanumeric_replacement: r"\1" # Keeps only one instance of the repeated character

normalizes_newlines: r"\n\s*\n" # Regex pattern to normalize multiple blank lines into a single paragraph break
two_lines: "\n\n" # Replacement string for normalized paragraph breaks
