path: "./data/datasets/books/"
file_extension: ".epub"

whitespace: r"\s+"
whitespace_replacement: " "

url: r"http\S+|www\S+"
url_replacement: ""

non_alphanumeric: r"[^A-Za-z0-9\s\.,;:\'\"\?\!\-]"
non_alphanumeric_replacement: ""

consecutive_non_alphanumeric: r"([^A-Za-z0-9\s])\1+"
consecutive_non_alphanumeric_replacement: r"\1"

newlines_pattern: r"\n\s*\n"
two_lines: "\n\n"
