text_embedding:
  model_name: "all-MiniLM-L6-v2" # Name of the sentence-transformer model to use for generating embeddings
  show_progress: True # Whether to show a progress bar during embedding generation

embed_documents:
  embeddings_path: "./data/embeddings/"
  index_name: "milvus.db"
